Generate emoji from backend
codex-team/reactions.backend pull request #10
Opened 2019-02-05 13:59 UTC by cabad11

add pictures

2019-02-14 05:25 UTC, neSpecc commented
Давай подумаем, может быть стоит передавать картинки на клиент в виде base64? Чтобы снизить трафик на наш бэкенд.

И еще, можем добавить кэширование для запросов на картинки? Мне кажется считывающие файлов с диска — дорогая операция и может все нехило загрузить, если какой-нибудь BBC или New York Times встроит наш модуль к себе.

2019-02-14 05:27 UTC, neSpecc commented
И еще вопрос — что будет, если кто-то передаст новую emoji (они появляются 1-2 раза в год), картинки для которой у нас нет? Нужно как-то эту ситуацию обработать.

2019-02-14 05:29 UTC, neSpecc commented
Откуда взята база картинок? Реально ли написать скрипт, который будет подтягивать новые картинки для появившихся emoji? Типа вызвал `yarn run update_emoji` и он подкачал новые файлы

2019-03-05 05:57 UTC, neSpecc requested changes
— добавить заглушку для неподдерживаемых emoji

2019-03-18 05:12 UTC, neSpecc submitted a review, later dismissed
— добавить issues

2019-03-20 09:55 UTC, neSpecc commented
— картинки слишком маленькие, нужно 80x80 минимум

2019-03-30 19:38 UTC, talyguryn requested changes
удалить файл .DS_Store, а следующим коммитом добавить его в игнор

2019-03-31 14:14 UTC, neSpecc submitted a review, later dismissed

2019-04-02 05:19 UTC, neSpecc approved these changes

2019-04-15 05:40 UTC, talyguryn requested changes
в целом работает

2019-04-15 05:40 UTC, talyguryn commented on src/routes/index.ts
> +      res.sendFile(path.resolve('./emoji/' + req.url));
можно тут указать пусть через `__dirname`?
```suggestion
      res.sendFile(path.resolve(__dirname, '..', '..', 'emoji', req.url));
```

2019-04-15 05:40 UTC, talyguryn commented on src/routes/index.ts
> +      res.sendFile(path.resolve('./emoji/' + req.url));
на вопрос "зачем" отвечу, что так понятнее, куда лезем

2019-04-17 05:37 UTC, talyguryn approved these changes

2019-04-17 09:01 UTC, gohabereg approved these changes

2019-04-17 16:42 UTC, merged