Anti cheat protection
codex-team/reactions.backend pull request #12
Opened 2019-02-11 05:20 UTC by DorofeevMark

https://github.com/codex-team/reactions.backend/issues/11

2019-02-15 10:05 UTC, neSpecc requested changes

2019-02-15 10:05 UTC, neSpecc commented on src/actions/index.ts
> +      && token._id.toString() === message.token
может вынести эту проверку в класс VoteToken? будут методы 

```
VoteToken.get(domain, userId);

VoteToken.check(message.token);
```

а то index.ts разрастается

2019-02-15 10:05 UTC, neSpecc commented on src/constants/token.ts
> +export const TOKEN_LIFETIME_IN_MINUTES = 10;
почему не в env?

2019-02-15 10:05 UTC, neSpecc commented on src/socket.ts
> +      console.log(message);
лог забыл убрать

2019-02-15 10:05 UTC, neSpecc commented on src/storage/index.ts
> +   * Returns token
тут надо описать предназначение токена

2019-02-19 20:29 UTC, gohabereg submitted a review, later dismissed

2019-02-27 17:28 UTC, neSpecc requested changes

2019-02-27 17:28 UTC, neSpecc commented on src/storage/index.ts
> +    await this.createTTLIndex(collection, 'startDate', Number(process.env.TOKEN_LIFETIME_IN_MINUTES) * 60);
а эта штука будет выполняться при каждом запросе? по идее ее надо один раз сделать?

2019-03-05 06:58 UTC, neSpecc submitted a review, later dismissed

2019-03-05 15:03 UTC, gohabereg approved these changes

2019-03-05 15:03 UTC, neSpecc approved these changes

2019-03-13 12:16 UTC, merged