Emoji images
codex-team/reactions.backend pull request #13
Opened 2019-03-29 04:22 UTC by DorofeevMark

Added images

2019-03-30 19:43 UTC, talyguryn requested changes
как были получены все эти файлы? какой скрипт для генерации надо вбить или скачать всю папку откуда-то? нужны хоть какие-то доки, чтобы иметь возможность обновить базу картинок

2019-03-31 05:13 UTC, DorofeevMark commented
> как были получены все эти файлы? какой скрипт для генерации надо вбить или скачать всю папку откуда-то? нужны хоть какие-то доки, чтобы иметь возможность обновить базу картинок

https://github.com/github/gemoji

2019-04-01 16:48 UTC, neSpecc approved these changes

2019-04-01 17:23 UTC, talyguryn approved these changes

2019-04-01 17:36 UTC, merged