Initial
codex-team/reactions.backend pull request #2
Opened 2018-11-13 19:51 UTC by DorofeevMark

Added a basic structure

2018-11-13 19:56 UTC, gohabereg requested changes
Давай еще сразу выставим cors, чтобы потом с этим не париться

2018-11-13 19:56 UTC, gohabereg commented on src/models/Reactions.ts
> +    constructor(id: string,
Тут тогда тоже лучше перенести строчку

2018-11-13 19:56 UTC, gohabereg commented on src/models/Reactions.ts
> +    constructor(id: string,
И пробел после `constructor`

2018-11-13 19:56 UTC, gohabereg commented on src/routes/index.ts
> +        this.app = express();
express() разве синглтон?

2018-11-13 19:56 UTC, gohabereg commented on src/routes/index.ts
> +            this.actions.getReactions().then((reactions: Reactions) => {
Давай использовать async/await

2018-11-13 19:56 UTC, gohabereg commented on src/socket.ts
> +import {Socket} from "net";
Почему не из `@types/socket.io`?

2018-11-14 16:52 UTC, gohabereg requested changes

2018-11-14 16:52 UTC, gohabereg commented on src/socket.ts
> +import * as ioEntry from "socket.io";
Думаю, можно объединить импорты
```
import io, {Socket} from "socket.io"
```

2018-11-14 16:55 UTC, DorofeevMark commented on src/socket.ts
> +import * as ioEntry from "socket.io";
Я специально разделил, потому что один импортирует из socket.io, а второй из @types/socket.io, что слегка запутывает

2018-11-14 17:01 UTC, gohabereg submitted a review, later dismissed

2018-11-14 17:05 UTC, neSpecc requested changes
код не продокументирован

2018-11-16 11:33 UTC, gohabereg approved these changes

2018-11-17 13:21 UTC, neSpecc approved these changes

2018-11-19 16:39 UTC, merged