Database
codex-team/reactions.backend pull request #3
Opened 2018-11-17 07:17 UTC by Bavian

2018-11-17 13:37 UTC, gohabereg requested changes

2018-11-17 13:37 UTC, gohabereg commented on src/database/index.ts
> +    const collection = await this.getCollection(collectionsName)
Если getCollection вернет undefined, то в остальных методах будут ошибки. Лучше пробрасывать exception наверх, чтобы внешний код сам их обрабатывал

2018-11-17 13:37 UTC, gohabereg commented on src/database/index.ts
> +    return collection.find(query).toArray()
Это будет работать? Там не надо сначала подождать выполнение find, прежде чем вызывать toArray?

2018-11-17 13:37 UTC, gohabereg commented on src/database/index.ts
> +    await collection.updateMany(query, updater)
Лучше сделать
```
return collection.updateMany(query, updater)
```

Тогда пользователь сможет обработать результат

2018-11-17 13:37 UTC, gohabereg commented on src/database/index.ts
> +  public async update (collectionsName: string, query: object, updater: object): Promise<void> {
Почему collection**s**Name?

2018-11-17 13:37 UTC, gohabereg commented on src/database/index.ts
> +    await collection.deleteMany(query)
Аналогично, лучше вернуть результат запроса

2018-11-17 13:37 UTC, gohabereg commented on src/index.ts
> +console.log('Hello_world')
Надо будет дождаться, пока смерджат Initial реквест и притянуть мастера

2018-11-17 13:37 UTC, gohabereg commented on src/storage/index.ts
> +const standartUrl = 'mongodb://localhost:27017'
Лучше default

2018-11-17 13:37 UTC, gohabereg commented on src/storage/index.ts
> +const countersPostfix = '_counters'
Вот эти все константы можно вынести в env файл. Почитай про dot-env

2018-11-17 13:37 UTC, gohabereg commented on src/storage/index.ts
> +    return await this.isCountersExist(domain, article);
Зачем такие конструкции? Почему сразу не вызвать isCountersExists?

2018-11-17 13:37 UTC, gohabereg commented on src/storage/index.ts
> +    await this.addCounters(domain, article, reactions);
Почему сразу не вызвать addCounters?

2018-11-17 13:37 UTC, gohabereg commented on src/storage/index.ts
> +    await this.database.insert(domain + countersPostfix, this.makeCountersData(article, true, reactions))
Лучше вынести результат this.makeCountersData в отдельную переменную, чтобы сократить длину строчки

2018-11-17 13:37 UTC, gohabereg commented on src/storage/index.ts
> +      const answerFromDb = await this.database.find(domain + countersPostfix, this.makeCountersData(article));
Для таких штук реализуй в классе Database метод findOne

2018-11-17 13:37 UTC, gohabereg commented on src/storage/index.ts
> +  private makeCountersData(article: string, toInsert: boolean=false, reactions: number=0): object {
Пробелы вокруг `=`

2018-11-17 13:49 UTC, Bavian commented on src/database/index.ts
> +    return collection.find(query).toArray()
Работает, find возвращает специальный объект, а не Promise.
Ну и без простейших тестов, я бы не стал открывать pull request :)

2018-11-17 13:52 UTC, Bavian commented on src/database/index.ts
> +  public async update (collectionsName: string, query: object, updater: object): Promise<void> {
Collection's name - чтобы указать принадлежность, но я понял, что здесь не так, придумаю новое название

2018-11-17 13:52 UTC, Bavian commented on src/database/index.ts
> +    await collection.updateMany(query, updater)
В каком плане 'обработать"?

2018-11-17 13:57 UTC, Bavian commented on src/storage/index.ts
> +    await this.addCounters(domain, article, reactions);
Это заложенная логика на будущее
Если, например, мы решим добавить комментарии к статьям, нам нужно будет улучшить методы работы со статьями, а счетчики трогать не нужно будет

2018-11-17 14:00 UTC, Bavian commented on src/storage/index.ts
> +      const answerFromDb = await this.database.find(domain + countersPostfix, this.makeCountersData(article));
Не понимаю в чем смысл, метод find работает как findOne в mongodb
Именую специально, как не в Mongodb, чтобы в случае перехода, не оставалась связи с ней двже в названиях

2018-11-18 12:06 UTC, gohabereg commented on src/storage/index.ts
> +    await this.addCounters(domain, article, reactions);
Может тогда разделить на ReactionsStorage и UsersStorage? Просто сейчас очень большой класс получается

2018-11-18 12:07 UTC, gohabereg commented on src/database/index.ts
> +    await collection.updateMany(query, updater)
Монго для всех операций возвращает какой-нибудь результат, который может понадобиться пользователю. Можно или сразу кидать результат в return, либо как-то обрабатывать, чтобы он был независим от моего. Но пока будет достаточно и 1 варинта

2018-11-18 19:05 UTC, Bavian commented on src/storage/index.ts
> +    await this.addCounters(domain, article, reactions);
Операция удаления статьи также удаляет и всю информацию о голосах всех пользователей, поэтому разделение логически не очень будет соответствовать. ReactionStorage полезет в UsersStorage
А большой класс - это проблема? Я постарался расставить методы так, чтобы был порядок и связанные вещи находились друг с другом, плюс очень много приватных методов, методов для управления Storage не так много

2018-11-19 17:40 UTC, Bavian commented on src/database/index.ts
> +    await collection.updateMany(query, updater)
Это невозможно Storage.vote вызывает database.update дважды с разными аргументами

2018-11-19 19:42 UTC, gohabereg requested changes

2018-11-19 19:42 UTC, gohabereg commented on src/database/index.ts
> +      throw e
Этот try catch не имеет смысла

2018-11-19 19:42 UTC, gohabereg commented on src/database/index.ts
> +      throw e
Тоже нет смысла

2018-11-19 19:42 UTC, gohabereg commented on src/database/index.ts
> +      throw e
И во всех аналогичных ситуациях. Нет смысла ловить ошибку и тут же кидать ее дальше

2018-11-19 19:42 UTC, gohabereg commented on src/index.ts
> +console.log('Hello_world')
Притяни мастера

2018-11-19 19:42 UTC, gohabereg commented on src/storage/index.ts
> +const standartUrl = 'mongodb://localhost:27017'
Переименуй в defaultUrl

2018-11-19 19:42 UTC, gohabereg commented on src/storage/index.ts
> +  public async addArticle (domain: string, article: string, reactions: number): Promise<void> {
Мне не очень нравятся названия Article и Counter. Если с Article более-менее понятно, то Counter вообще не дает представления о том, что делают функции.

У нас везде опросы называются Reactions, а отдельные вариант - Reaction

2018-11-20 22:21 UTC, gohabereg requested changes

2018-11-20 22:21 UTC, gohabereg commented on src/database/index.ts
> +    await collection.updateMany(query, updater)
Так не важно, сколько раз вызывает. Просто возвращаешь значение, которое вернуло mongodb

2018-11-20 22:21 UTC, gohabereg commented on src/storage/index.ts
> +dotenv.config({path: 'vars/database.env'})
Это лучше перенести в файл - точку входа

2018-11-20 22:21 UTC, gohabereg commented on src/storage/index.ts
> +  public async getReactions(domain: string, article: string): Promise< Array<number> > {
Лучше назвать тогда articleId или reactionId. Упомянуть id в названии

2018-11-20 22:21 UTC, gohabereg commented on src/storage/index.ts
> +  private getReactionsDomain(domain: string): string {
Функция не домен возвращает. Лучше тогда getReactionsCollectionName

2018-11-20 22:21 UTC, gohabereg commented on src/storage/index.ts
> +      result.reactions = new Array<number>(length)
Вообще, хорошо бы привязывать голоса к юникод символу эмодзи. Если пользователь вдруг поменяет порядок или вообще заменит эмодзи, то все поломается

2018-11-20 22:21 UTC, gohabereg commented on src/storage/index.ts
> +    for (let i = array.length; i <= index; i++) {
Для этого в есть метод `fill`

2018-11-20 22:21 UTC, gohabereg commented on src/storage/index.ts
> +  public async vote(domain: string, article: string, user: string, index: number): Promise<void> {
А зачем тогда метод addUserReaction?

2018-11-21 09:05 UTC, Bavian commented on src/database/index.ts
> +    await collection.updateMany(query, updater)
Ну в Database это сработает
Но в Storage я не смогу вернуть результат

2018-11-29 15:10 UTC, gohabereg submitted a review, later dismissed

2018-12-23 11:54 UTC, neSpecc commented on .env.sample
> +REACTIONS_PREFIX=reactions
надо добавить комменты

2018-12-23 11:54 UTC, neSpecc commented on src/models/Reactions.ts
> +  public reaction?: number;
не описано свойство

2018-12-24 13:53 UTC, gohabereg approved these changes

2018-12-24 13:57 UTC, neSpecc approved these changes

2018-12-24 13:57 UTC, merged